version: '3.8'

services:
  python-app:
    container_name: python-app-container
    image: jobinaj/python-app:test
    restart: always
    ports:
      - "5000:5000"
    environment:
      - ENV=production
    working_dir: /app
    volumes:
      - ./7_final_code_background_music_image.py:/app/7_final_code_background_music_image.py
