name: Build and Deploy Python App

on:
  push:
    branches:
      - main  # Adjust if using a different branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Debug Secrets (Check if they are available)
        run: echo "Docker Username: ${{ secrets.DOCKER_USERNAME }}"

      - name: Enable Docker CLI authentication
        run: echo "{ \"credsStore\": \"desktop\" }" > ~/.docker/config.json

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/python-snake-game:test .
          docker push ${{ secrets.DOCKER_USERNAME }}/python-snake-game:test

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Set up SSH Key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key
          chmod 600 private_key

      - name: Deploy using Docker Compose
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key ubuntu@${{ secrets.SERVER_IP }} << 'EOF'
            docker login -u "${{ secrets.DOCKER_USERNAME }}" -p "${{ secrets.DOCKER_PASSWORD }}"
            docker pull ${{ secrets.DOCKER_USERNAME }}/python-snake-game:test
            docker-compose up -d --force-recreate
          EOF
